### ISSUE TITLE
Curve worker filter and match logics

### ISSUE THREAD

**Issue by pseudoyu** [RSS3-Network/Node#552]
### What is expected?

Filter Curve transaction precisely and structure them in our DSL API.

### What is actually happening?

Lots of unknown transactions appeared in our API response.

### Additional info

```shell
Transactions like https://etherscan.io/tx/0x0000638bb7e8cbad7d73a98dab0681131c1a559008490c3bbef2e0cf8725ef00 are handled into unknown curve transactions, which is not expected.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/rss3-network/node/issues) to ensure this bug has not already been reported

**Comment by brucexc** [comment]
According to the information from https://etherscan.io/tx/0x0000638bb7e8cbad7d73a98dab0681131c1a559008490c3bbef2e0cf8725ef00, this is a Uniswap transaction. The issue described here should be the same as the one mentioned in https://github.com/RSS3-Network/Node/issues/608. Therefore, the problem description in this issue is inaccurate, and it should be corrected to "Filtering Uniswap transactions." @pseudoyu

**Comment by brucexc** [comment]
https://github.com/RSS3-Network/Node/issues/667
